Repository googleapis/nodejs-recaptcha-enterprise, pull requests merged in 2019-05, with the labels that each got.

#3 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#5 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#4 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#6 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#1 build: nyc config with --all enabled
  .nycrc
  __pycache__/synth.cpython-36.pyc
  synth.metadata
Labels: cla: yes

#7 fix: do not retry request on DEADLINE_EXCEEDED
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  __pycache__/synth.cpython-36.pyc
  src/v1beta1/recaptcha_enterprise_service_v1_beta1_client_config.json
  synth.metadata
Labels: cla: yes

#9 chore: remove __pycache__
  __pycache__/synth.cpython-36.pyc
Labels: cla: yes

#10 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1beta1/recaptcha_enterprise_service_v1_beta1_client_config.json
  synth.metadata
Labels: cla: yes

#11 chore(boostrapping): bootstrapping tests, samples, and docs
  .gitignore
  README.md
  package-lock.json
  package.json
  samples/.eslintrc
  samples/README.md
  samples/package.json
  samples/quickstart.js
  samples/test/.eslintrc
  samples/test/samples.test.js
  src/index.js
  src/v1beta1/recaptcha_enterprise_service_v1_beta1_client.js
  synth.metadata
  system-test/.eslintrc
  system-test/test.js
  test/.eslintrc
  test/gapic-v1beta1.js
Labels: cla: yes

#20 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#21 docs: fix import example
  src/v1beta1/recaptcha_enterprise_service_v1_beta1_client.js
  synth.metadata
Labels: cla: yes

#23 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#24 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1beta1/recaptcha_enterprise_service_v1_beta1_client.js
  synth.metadata
Labels: cla: yes

#25 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#26 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#27 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#28 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
