Repository googleapis/nodejs-recaptcha-enterprise, pull requests merged in 2020-11, with the labels that each got.

#220 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: recaptchaenterprise, automerge, cla: yes, context: full

#222 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/recaptcha_enterprise_service_client.ts
  src/v1beta1/recaptcha_enterprise_service_v1_beta1_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: recaptchaenterprise, automerge, cla: yes

#221 build: add RecaptchaEnterpriseServiceClient type
  synth.metadata
Labels: api: recaptchaenterprise, automerge, cla: yes, context: none

#226 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/recaptcha_enterprise_service_client.ts
  src/v1beta1/recaptcha_enterprise_service_v1_beta1_client.ts
  synth.metadata
Labels: api: recaptchaenterprise, cla: yes, context: partial

#228 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: recaptchaenterprise, automerge, cla: yes, context: full
