Repository googleapis/nodejs-recaptcha-enterprise, pull requests merged in 2020-05, with the labels that each got.

#169 fix: regen protos and tests, formatting
  protos/protos.js
  synth.metadata
  test/gapic_recaptcha_enterprise_service_v1.ts
  test/gapic_recaptcha_enterprise_service_v1_beta1_v1beta1.ts
Labels: automerge, cla: yes

#170 chore: linting rules
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#171 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 fix!: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
Labels: cla: yes
